### ISSUE TITLE
Last Online time can be incorrect

### ISSUE THREAD

**Issue by zachpmanson** [alexbarker234/sale-savant#1]
For user pavo-etc the last online time comes up as 53 years, something is defaulting to the unix epoch timestamp.

![image](https://github.com/alexbarker234/sale-savant/assets/24368336/90ead7ec-f078-4408-9e98-b129a994ad04)

**Comment by alexbarker234** [comment]
Kind of fixed - it was essentially a placeholder to make it look less empty. It's now been replaced with a count of games in your wishlist/games on sale.

I think if your profile wasn't public, then it would not be able to find your last online date and I didn't account for that because steam API doco is garbage 👍
